---
- name: "GATHER INTERFACE STATUS FROM CISCO SWITCHES"
  hosts: switches
  gather_facts: false  
  tasks:
    - name: " 101- Run show ip interface on remote devices "
      cisco.ios.ios_command:
        commands: 
          # - show ip interface brief
          - show runn
      register: interface_output
    - name: "1010 - OUTPUT INTERFACE BRIEF"
      debug:
        var: interface_output
    

    
    # - name: " 102- Parse interface data using TextFSM "
    #   ansible.builtin.set_fact:
    #     parsed_interfaces: "{{ interface_output.stdout[0] | parse_cli_textfsm('ntc-templates/ntc_templates/templates/cisco_ios_show_ip_interface_brief.textfsm') }}"
    #bash
    #source pyats_env/bin/activate

    # - name: " 103- Read in parse_genie role "
    #   include_role:
    #     name: clay584.parse_genie

    # - name: " 104- Parse interface data using genie 
    #   set_fact:
    #     parsed_interfaces: "{{ interface_output.stdout[0] | parse_genie(command='show ip interface brief', os='ios') }}"
    # # - name: Display Output interface
    # #   debug:
    # #     var: parsed_interfaces
    
    # # - name: " 105- Save parsed data to JSON file for Python script "
    # #   copy:
    # #     dest: "/mnt/d/networking/network-automation/boot-camp/ansible-may-24/Ansible/Playbooks/parsed_interfaces.json"
    # #     content: "{{ parsed_interfaces | to_nice_json }}"

    # - name: " 106- Execute Python script to write data to Excel "
    #   command: "python3 /mnt/d/networking/network-automation/boot-camp/ansible-may-24/Ansible/Playbooks/write_excel.py"
    #   register: result
    
    # - name: " 107- Execute Python script to upload the file to Google Drive "
    #   command: python3 /mnt/d/networking/network-automation/boot-camp/ansible-may-24/Ansible/Playbooks/upload_to_google_drive.py
    #   when: result.changed  # Only run if the Excel file was created successfully

    # - name: " 108- Format the data into CSV "
    #   set_fact:
    #     csv_data: |
    #       switch_name,status,protocol,ip_address
    #       {% for interface, data in parsed_interfaces.interface.items() %}
    #       {{ inventory_hostname }},{{ data.status }},{{ data.protocol }},{{ data.ip_address }}
    #       {% endfor %}

    # - name: " 109- Export interface data to CSV "
    #   copy:
    #     dest: "/mnt/d/networking/network-automation/boot-camp/ansible-may-24/Ansible/Playbooks/switch_interfaces_report_{{ inventory_hostname }}.csv"
    #     content: "{{ csv_data }}"
