[switches]
#setting up for genie
;switch1 ansible_host=192.168.10.147 ansible_user=sw1 ansible_password=sw1 ansible_network_os=ios ansible_connection=network_cli ansible_become=yes ansible_become_method=enable ansible_become_password=sw1
;switch2 ansible_host=192.168.10.148 ansible_user=sw2 ansible_password=sw2 ansible_network_os=ios ansible_connection=network_cli ansible_become=yes ansible_become_method=enable ansible_become_password=sw2
switch1 ansible_host=192.168.10.147 ansible_user=sw1 ansible_password=sw1 ansible_network_os=ios
switch2 ansible_host=192.168.10.148 ansible_user=sw2 ansible_password=sw2 ansible_network_os=ios
; switch1 ansible_host=192.168.10.147 ansible_user=sw1 ansible_password=sw1 ansible_network_os=ios ansible_connection=network_cli
; switch1 ansible_host=192.168.10.147 ansible_user=sw1 ansible_password=sw1 ansible_network_os=ios ansible_connection=network_cli ansible_become=yes ansible_become_method=enable ansible_become_password=sw1
; switch2 ansible_host=192.168.10.148 ansible_user=sw2 ansible_password=sw2 ansible_network_os=ios ansible_connection=network_cli
; switch3 ansible_host=192.168.10.149 ansible_user=sw3 ansible_password=sw3 ansible_network_os=ios ansible_connection=network_cli

