
---
- name: Play A
  hosts: localhost
  gather_facts: false
  vars:
    device_type: "Router"
    devices:
      - "R1"
      - "R2"
      - "R3"
    device_creds:
      username: "USER-ABC"
      Password: "PASS-ABC"
    
    ip: " 10.20.30.40 "
    ip_list:
      - " 10.20.30.40 "
      - " 20.30.40.50 "
      - " 30.40.50.60 "

  tasks:
    - name: "01 - PRINTING DEVICE TYPE"
      debug:
        #var: "device_type[0:2]"
        # msg: "{{ device_type[0:2] }}"
        # msg: "device_type[0:2]"
        #var: "device_type | upper"
        #var: "device_type[0:2] | upper"
        #msg: "{{ device_type | upper }}"
        #msg: "{{ device_type[0:2] | upper }}"
        #msg: "{{ device_type | upper | lower | upper }}"
        #var: "{{ device_type | upper | lower | upper }}" #By mistake put jinja templating in var 
        #var: "device_type | upper | lower | upper"
        #msg: "{{ device_type.upper() }}"
        #var: "device_type.upper()"
        #msg: "Device name is : {{ device_type.upper() }}"
        #msg: "Device name is : {{ device_type.upper().replace('ROU', 'my rou') }}"
        var: "device_type | upper | replace('ROU', 'my rou')" #passing output as input to other filter

    - name: "02 - PRINTING DEVICE DATA"
      debug:
        #var: "devices"
        #var: "devices[1]"
        #var: "devices[0:2]"
        #msg: "{{ devices }}"
        msg: "{{ devices[0:2] }}"

    - name: "03 - PRINTING DEVICE CREDS"
      debug:
        #var: "device_creds"
        #var: "device_creds.username"
        #var: "device_creds | username " >>>> Not working
        #var: "device_creds['username']"
        #msg: "USername is : {{ device_creds['username'] }}"
        var: "device_creds['username'][0:4]"

    - name: "04 - PRINTING DEVICE IP"
      debug:
        #var: "ip"
        #var: "ip_list"
        #var: "ip.strip()"
        #var: "ip.isalpha()"
        #var: "ip.strip().split('.')"
        #msg: "{{ ip.strip().split('.') }}"
        #var: "ip.strip().split('.')[2]"
        var: "'.'.join(ip.strip().split('.'))"
        