#Standard practice is to put everything in quote task name and var value and better to number task to identify for troubleshooting
---
- name: Play A
  hosts: localhost
  gather_facts: false
  vars:
    device_type: "Router"
    devices:
      - "R1"
      - "R2"
      - "R3"
    device_creds:
      username: "abc"
      Password: "123"

  tasks:
    - name: "01-PRINTING DEVICE TYPE"
      debug:
        var: device_type

    - name: 02- PRINTING DEVICE DATA
      debug:
        var: "devices"

    - name: "03- PRINTING DEVICE CREDS"
      debug:
        var: "device_creds"

#remaining set_fact