---
- hosts: localhost
  become: true
  tasks: 
    - name: user add in groups
      ansible.builtin.user: 
        name: "{{ item }}"
        state: present 
      #loop: "{{ lookup('ansible.builtin.file', '/home/aadarsh/ansible/playbook/users.txt').split() }}"
      loop: "{{ query('lines', 'cat /home/aadarsh/ansible/playbook/users.txt') }}"
 

