---
- hosts: localhost
  become: true
  tasks: 
    - name: Install ftp and httpd
      yum:
        name:
          - ftp
          - httpd
        state: installed  
    - name: yum with loop
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - ftp
        - httpd

