---
- name: Get basic device info
  hosts:  switches, routers     #"{{ hostname }}" #switches # network
  gather_facts: false

  tasks:
    - name: Print inventory name (logical name)
      debug:
        msg: "Device Name: {{ inventory_hostname }}"

    - name: Print management IP
      debug:
        msg: "Management IP: {{ ansible_host }}"





# ansible-playbook get-sw-info.yaml -i ../inv/inventory.ini --limit=SW2
# ansible-playbook get-sw-info.yaml -i ../inv/inventory.ini -e hostname=SW1