---
- name: Play A
  hosts: localhost
  gather_facts: false

  vars:
    devices:
      - R1
      - R2
      - R3

  tasks:
    - name: "10 MY TASK"
      debug:
        msg: "Hello world for Ansible"

    - name: "20 MY Loop TASK using loop"
      debug:
        var: item
      loop: "{{ devices }}"

    - name: "30 MY Loop TASK with direct list"
      debug:
        var: item
      loop:
        - SW1
        - SW2
        - SW3

    - name: "40 MY Loop TASK with inline list"
      debug:
        var: item
      loop: ["FW1", "FW2", "FW3"]
