---
- name: Deployement of WebServer
  hosts: servera
  gather_facts: false
  tasks: 
    - name: create directory /tmp/data
      ansible.builtin.file:
        path: /tmp/data
        state: directory
    - name: copy file /etc/fstab into /tmp/data 
      copy:
        src:  /etc/fstab
        dest: /tmp/data
    - name: restarted crond
      ansible.builtin.service:
        name: crond
        state: started
        enabled: yes

- name: Creating an user on serverb
  hosts: serverb
  gather_facts: false
  tasks: 
    - name: creating an user mohan on serverb
      ansible.builtin.user:
        name: mohan
        state: present
        group: wheel

