---
- hosts: servera
  gather_facts: false
  tasks: 
    - file:
        path: /tmp/data
        state: directory
    - copy:
        src:  /etc/fstab
        dest: /tmp/data
    - service:
        name: crond
        state: reloaded
