---
- name: SWITCH INTERFACE INFORMATION
  hosts: switches
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "1010 PRE-CHECK"
      import_tasks: tasks/check.yaml
      register: ver

    - name: "1020 DISPLAY PRE-CHECK"
      debug:
        var: ver["stdout_lines"][1]

    - name: "1030 CONFIG SWITCH INTERFACE AND DESCRIPTION"
      cisco.ios.ios_config:
        lines:
          - description test NETWORK AUTOMATION
        parents: interface Gi0/1

    - name: "1040 POST CHECK"
      import_tasks: tasks/check.yaml
      register: ver

    - name: "1050 DISPLAY POST CHECK"
      debug:
        var: ver["stdout_lines"][1]

















# ---
# - name: Play A
#   hosts: switches
#   gather_facts: false
#   connection: network_cli

#   tasks:
#     - name: "1010 RUN SHOW VERSION ON REMOTE DEVICE"
#       cisco.ios.ios_command:
#         commands:
#           - show version
#           # - show ip inter brief # used for indexing mismatch, we don't do it randomly
#           - show inter description
#           - show ip inter br
#       register: ver

#     - name: "1020 DISPLAY IOS VERSION"
#       debug:
#         # var: ver.stdout_lines
#         var: ver["stdout_lines"][1]

#     - name: "1030 CONFIG SWITCH INTERFACE IP AND DESCRIPTION"
#       cisco.ios.ios_config:
#         lines:
#           - description test automation
#           - ip address 172.31.1.1 255.255.255.0
#         parents: interface Ethernet1
    
#     - name: "1040 RUN SHOW VERSION ON REMOTE DEVICE"
#       cisco.ios.ios_command:
#         commands:
#           - show version
#           - show inter description
#           - show ip inter br
#       register: ver

#     - name: "1050 DISPLAY IOS VERSION"
#       debug:
#         # var: ver.stdout_lines
#         var: ver["stdout_lines"][1]






# ---
# - name: Play A
#   hosts: switches
#   gather_facts: false
#   connection: network_cli

#   tasks:
#     - name: "1010 RUN SHOW VERSION ON REMOTE DEVICE"
#       cisco.ios.ios_command:
#         commands:
#           - show version
#       register: ver
   
#     - name: "1020 DISPLAY IOS VERSION"
#       debug:
#         # var: ver   # gives output string and list both to get rid of this use: stdout_lines
#         var:  ver["stdout_lines"]