- name: SWITCH INTERFACE INFORMATION
  hosts: switches
  gather_facts: true
  connection: network_cli

  tasks:
    - name: "10 PRINTING ANSIBLE USER"
      debug:
        msg: "{{ ansible_user }}"

    - name: "20 GET DEVICE INFO"
      cisco.ios.ios_facts:
        gather_subset: all
      register: output

    - name: "30 SET DEVICE FACTS"
      set_fact:
        sw_mgmt_ip: "{{ output['ansible_facts']['ansible_net_all_ipv4_addresses'][0] }}"
        sw_image: "{{ output['ansible_facts']['ansible_net_image'] }}"

    - name: "40 DEBUG STORED VALUES"
      debug:
        msg:
          - "Mgmt IP: {{ sw_mgmt_ip }}"
          - "Image: {{ sw_image }}"














# # using dot method


# - name: SWITCH INTERFACE INFORMATION
#   hosts: switches
#   gather_facts: false
#   connection: network_cli

#   tasks:
#     - name: "10 PRINTING ANSIBLE USER"
#       debug:
#         msg: "{{ ansible_user }}"

#     - name: "20 GET DEVICE INFO"
#       cisco.ios.ios_facts:
#         gather_subset: all
#       register: output

#     - name: "30 DEBUG DEVICE MGMT IP (FIRST IPV4)"
#       debug:
#         msg: "{{ output.ansible_facts.ansible_net_all_ipv4_addresses[0] }}"

#     - name: "40 SET SWITCH MGMT IP"
#       set_fact:
#         sw_mgmt_ip: "{{ output.ansible_facts.ansible_net_all_ipv4_addresses[0] }}"

#     - name: "50 DEBUG STORED MGMT IP"
#       debug:
#         var: sw_mgmt_ip













