################################
# SWITCHES
################################
[switches]
SW1 ansible_host=192.168.199.202
SW2 ansible_host=192.168.199.203
SW3 ansible_host=192.168.199.194

################################
# ROUTERS
################################
[routers]
R1 ansible_host=192.168.199.198
R2 ansible_host=192.168.199.195
R3 ansible_host=192.168.199.191

################################
# COMMON NETWORK VARIABLES
################################
[network:children]
switches
routers

[network:vars] # group vars 
ansible_user=netg
ansible_password=india
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
ansible_network_os=ios
