---
# running playbook for group
# - name: Play A
#   hosts: switches
#   gather_facts: false

#running playbook for indivisual switch - context base data pulling 
#usage command
# ansible-playbook -i inventory.ini managing_inventory.yaml
# limiting output without using variable and using host group
#ansible-playbook -i inventory.ini managing_inventory.yaml --limit "switch1"
#ansible-playbook -i inventory.ini managing_inventory.yaml --limit "switch1,switch2"

# - name: Play A
#   hosts: switch1 or switch2
#   gather_facts: false
#ansible-playbook -i inventory.ini managing_inventory.yaml

#running playbook with hosts as variable and being passed in extra var
# - name: Play A
#   hosts: "{{ switches }}"
#   gather_facts: false
#usage -ansible-playbook -i inventory.ini managing_inventory.yaml -e "switches=switch1"
#ansible-playbook -i inventory.ini managing_inventory.yaml -e "switches=switch2"

#running playbook with group called routers defined in inventory
# - name: Play A
#   hosts: routers
#   gather_facts: false

# #running playbook with multiple groups but limit can  be applied as well
# - name: Play A
#   hosts: routers, switches
#   gather_facts: false

#running playbook with group called device_group having 2 sub-groups routers and switches defined in inventory

# - name: Play A
#   hosts: device_group
#   gather_facts: false

#running playbook limiting to print only one group devices
#ansible-playbook -i inventory.ini managing_inventory.yaml --limit "routers"
#ansible-playbook -i inventory.ini managing_inventory.yaml --limit "switches"

#running ansible playbook and priting device data using default all group
# - name: Play A
#   hosts: all
#   gather_facts: false


  # tasks:
  #   - name: "01 - OUTPUT DEVICE TYPE"
  #     debug:
  #       var: ansible_host


#################Day 3 or playing with inventory##################################

- name: Play A
  hosts: switches
  gather_facts: false
  
  tasks:
    - name: "01 - OUTPUT DEVICE TYPE"
      debug:
        var: ansible_host

    - name: "01 - OUTPUT VLAN"
      debug:
        var: vlan

    - name: "03 - OUTPUT MESSAGE"
      debug:
        msg: "This playbook was triggered by servicenow "


#ansible-playbook -i inventory.ini managing_inventory.yaml
