#By mistake entered two tasks but second task is only running 
---
- name: Play A
  #hosts: localhost
  hosts: switches
  gather_facts: false
  vars:
    device: "Router"

  tasks:
    - name: Hello World
      debug:
        msg: "Hello World"

      #tasks:
    - name: Print var
      debug:
        var: device

  # tasks:
  #   - name: Print var
  #     debug:
  #       var: device

#remaining set_fact
