---
- name: Demonstrate all Cisco IOS modules with output registration
  hosts: switches
  gather_facts: no
  # gather_facts: yes
  collections:
    - cisco.ios
  tasks:
# # 1. ios_facts
    # - name: "1- Collect facts from Cisco devices"
      # cisco.ios.ios_facts: #comment line 6 & 7
#       ios_facts: #uncomment line 6 & 7 and comment 11
#         gather_subset:
#     #       - interfaces
#           # - config
#           - hardware
#       # register: interface_facts
#       # register: runn_config
#       register: hardware_details


#     # - name: "1.1. - OUTPUT INTERFACE FACTS"
#     # - name: "1.1. - OUTPUT Running config"
#     - name: "1.1. - OUTPUT hardware details"
#       debug:
#         # var: interface_facts
#         # var: runn_config
#         var: hardware_details
    #     # var: interface_facts.keys()
    #     # var: interface_facts.ansible_facts.keys()
    #     # var: interface_facts["ansible_facts"]["ansible_net_neighbors"]
    #     var: interface_facts.ansible_facts.ansible_net_neighbors

# 2. ios_config
    # - name: "2- Apply configuration to a Cisco device"
    #   ios_config:
    #     lines:
    #       - description Configured by Ansible
    #     parents:
    #       - interface Ethernet0/0
         
    #   register: config_output

    # - name: " 2.1. - Print configuration task result"
    #   debug:
    #     var: config_output
    
# 3. ios_banner
    # - name: " 3- Configure a banner message"
    #   ios_banner:
    #     banner: motd
    #     text: "*************************
    #     This is a private computer.Unauthorized access is prohibited.
    #     *******************************"
    #   register: banner_output

    # - name: " 3.1.- Print banner configuration result"
      # debug:
      #   var: banner_output

# 4. ios_command
    - name: " 4-Execute a show command"
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
    #       - show interface description
    # # #       - show vlan bri
    # #         # - show version
    # #         # - show version | i uptime | register 
      register: command_output

    - name: " 4.1.- Print command output"
      debug:
    #     var: command_output.stdout
       var: command_output

    # - name: Run custom Python script and parse output
    #   hosts: localhost  # Specify localhost here
    #   gather_facts: no  # Disable gathering facts as it's unnecessary for this task
    #   tasks:
    #     - name: Run custom Python script to parse output
    #       command: python3 parse_interfaces.py
    #       register: parsed_interfaces_output

    # - name: Show parsed interfaces
    #   debug:
    #     var: parsed_interfaces_output.stdout



#5.ios_static_route  ##### not working  indentation error not resolved       
  # - name: "5- Configure a static route"
  #   ios_static_route:
  #     network: 0.0.0.0
  #     netmask: 0.0.0.0
  #     gateway: 192.168.10.1
  #   register: static_route_output

  # - name: "5.1.- Print static route configuration result"
  #   debug:
  #     var: static_route_output    

# 6. ios_ping
    # - name: " 6- Perform a ping test "
    #   cisco.ios.ios_ping:
    #     dest: 8.8.8.8
    #   register: ping_output

    # - name: " 6.1.- Print ping results "
    #   debug:
    #     var: ping_output

#7.ios_vlan ##### not working  indentation error not resolved    
    # - name: "7- Create a VLAN"
    #   cisco.ios.ios_vlan:
    #     vlan_id: 900
    #     name: Test_Ansible_vlan
    #   register: vlan_output

    # - name: "7.1.- Print VLAN creation result"
    #   debug:
    #     var: vlan_output





   



