################################
# SWITCHES
################################
[switches]
SW1 ansible_host=192.168.199.188
SW2 ansible_host=192.168.199.189
SW3 ansible_host=192.168.199.190

################################
# ROUTERS
################################
[routers]
R1 ansible_host=192.168.199.187
R2 ansible_host=192.168.199.185
R3 ansible_host=192.168.199.186

################################
# COMMON NETWORK VARIABLES
################################
[network:children]
switches
routers

[network:vars]
ansible_user=netg
ansible_password=india
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
