---
- hosts: localhost
  become: true
  vars_files:
    - /home/aadarsh/ansible/playbook/pb-user_list.yaml
  tasks:
    - name: example of simple loop
      user:
        name: "{{ item }}"
        state: present
      with_items: "{{ myusers }}"

        
    - name: add groups
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ mygroups }}"
      


# with_items and loop are same thing and can be used any one of them.
