- name: example of command line
  hosts: all
  vars_prompt:
    - name: username
      prompt: "please give the username"
      private: no
    - name: mypass
      prompt: "please enter the password"
      #private: yes
  tasks: 
    - name: add user and apply password
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ mypass| password_hash ('sha512') }}"

